name: Test
on:
  pull_request:
  push:
    branches: [main, ci]
jobs:
  phpunit:
    name: PHP ${{ matrix.php }}, ${{ matrix.dependencies }}
    runs-on: ubuntu-latest
    continue-on-error: ${{ matrix.php == '8.3' }}
    strategy:
      fail-fast: false
      matrix:
        php: [8.1]
        dependencies: [lowest, highest]
    steps:
      - uses: actions/checkout@v3
      - uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
      - uses: ramsey/composer-install@v2
        with:
          dependency-versions: ${{ matrix.dependencies }}
      - run: vendor/bin/phpunit --testdox --colors=always
